version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    environment:
      - MONGO_URI=
      - SECRET_KEY=secret
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: